apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-redis
data:
  redis.conf: |+
    # Other cluster members need to be able to connect
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  clusterIP: None
  ports:
  - targetPort: 6379
    port: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis 
  serviceName: "redis"
  replicas: 3 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: ravennaras/wlb:redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
      - name: configmap-redis
        configMap:
          name: configmap-redis
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard-rwo
      resources:
        requests:
          storage: 1Gi
